create table if not exists public.dashboard_biometric_baseline (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  location_id text not null,
  plot_id text not null,
  treatment_id text,
  replication text,
  plot_label text,
  observation_day integer,
  date_of_observation date,
  plant_count_1m numeric,
  plant_count_5m numeric,
  plant_count_15m numeric,
  number_of_node numeric,
  node_length_cm numeric,
  millable_cane_count numeric,
  cane_girth_cm numeric,
  number_of_tillers numeric,
  number_of_leaves numeric,
  plant_height_cm numeric,
  leaf_length_cm numeric,
  leaf_breadth_cm numeric,
  germination_pct numeric,
  source_file text,
  source_sheet text,
  imported_at timestamptz not null default now()
);

create table if not exists public.dashboard_fertigation_baseline (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  day_after_planting integer,
  date date,
  n_kg numeric,
  p2o5_kg numeric,
  k2o_kg numeric,
  mn_mixture_kg numeric,
  urea_kg numeric,
  map_kg numeric,
  dap_kg numeric,
  white_potash_kg numeric,
  location_id text not null,
  plot_id text not null,
  treatment_id text,
  imported_at timestamptz not null default now()
);

create table if not exists public.dashboard_location_master (
  location_id text primary key,
  location_name text not null,
  location_short_name text,
  plot_type text,
  farmer_name text,
  village text,
  variety text
);

create table if not exists public.dashboard_plot_master (
  plot_id text primary key,
  location_id text not null,
  plot_name text,
  replication text,
  treatment_id text,
  extent_acre numeric,
  unique (location_id, plot_id)
);

create table if not exists public.dashboard_treatment_master (
  location_id text not null,
  treatment_id text not null,
  plot_label text,
  treatment_details text,
  primary key (location_id, treatment_id)
);

create table if not exists public.dashboard_crop_stage_split (
  location_id text not null,
  crop_stage text not null,
  days_after_planting text,
  n_pct numeric,
  p_pct numeric,
  k_pct numeric,
  primary key (location_id, crop_stage)
);

create table if not exists public.dashboard_fertilizer_stock (
  location_id text not null,
  fertilizer text not null,
  total_kg numeric,
  available_bags numeric,
  primary key (location_id, fertilizer)
);

create index if not exists dashboard_biometric_location_day_idx
  on public.dashboard_biometric_baseline (location_id, observation_day);
create index if not exists dashboard_biometric_location_treatment_idx
  on public.dashboard_biometric_baseline (location_id, treatment_id);
create index if not exists dashboard_fertigation_location_day_idx
  on public.dashboard_fertigation_baseline (location_id, day_after_planting);
create index if not exists dashboard_fertigation_location_treatment_idx
  on public.dashboard_fertigation_baseline (location_id, treatment_id);

create index if not exists field_entries_approved_dashboard_idx
  on public.field_entries (location_code, observation_day, treatment)
  where status = 'Approved';
create index if not exists athani_entries_approved_dashboard_idx
  on public.athani_field_entries (location_code, observation_day, treatment)
  where status = 'Approved';
create index if not exists anthiyur_entries_approved_dashboard_idx
  on public.anthiyur_field_entries (location_code, observation_day, treatment)
  where status = 'Approved';

alter table public.dashboard_biometric_baseline enable row level security;
alter table public.dashboard_fertigation_baseline enable row level security;
alter table public.dashboard_location_master enable row level security;
alter table public.dashboard_plot_master enable row level security;
alter table public.dashboard_treatment_master enable row level security;
alter table public.dashboard_crop_stage_split enable row level security;
alter table public.dashboard_fertilizer_stock enable row level security;

revoke all on public.dashboard_biometric_baseline from anon, authenticated;
revoke all on public.dashboard_fertigation_baseline from anon, authenticated;
revoke all on public.dashboard_location_master from anon, authenticated;
revoke all on public.dashboard_plot_master from anon, authenticated;
revoke all on public.dashboard_treatment_master from anon, authenticated;
revoke all on public.dashboard_crop_stage_split from anon, authenticated;
revoke all on public.dashboard_fertilizer_stock from anon, authenticated;

comment on table public.dashboard_biometric_baseline is 'Canonical immutable import of the original biometric CSV baseline.';
comment on table public.dashboard_fertigation_baseline is 'Canonical immutable import of the original fertigation CSV baseline.';
